- package.json
- packages/adapter-elasticsearch/adapter.js
- packages/adapter-elasticsearch/adapter_test.js
- packages/adapter-elasticsearch/async-fetch.js
- packages/adapter-elasticsearch/index.js
- packages/adapter-elasticsearch/index_test.js
- packages/adapter-elasticsearch/package.json
- packages/adapter-elasticsearch/paths.js
- yarn.lock
closes #85 
First pass at an Elasticsearch adapter. I left some open questions as `TODOs` in the adapter file that we can address in later iterations of the adapter.
One thing that I went back and forth on was determining a meaningful way to use the `mappings`, as specified by the Search Port for `createIndex`. Because Elasticsearch requires `type` for each property, and that's not part of the Search Port, I felt that I couldn't do much with `mappings`. For now, I just made it such that every index created in Elasticsearch uses [dynamic mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html#_dynamic_mapping).
Open to suggestions on all these changes. Thanks. 😃
> Elasticsearch Adapter #85

- packages/nodejs-client/index.js
- packages/nodejs-client/index_test.js
Modified the queue API to accept specific app names for both the creation of the queue and the posting of the job
> feat: Enable the NodeJS Client Queue API to specify the Queue Name (#258)

- packages/app-opine/deps.js
- packages/app-opine/mod.js
- packages/app-opine/router.js
This PR basically moves the "guts" of the hyper `opine` app into a `opine` `Router`. Then cleans up some of the code ie. environment variables references at the top of the function, etc.
this will enable pulling in just the router, which is able to merge route params, instead of the entire opine instance, which is not capable of merge route parameters.
`mod.js` still exports a standalone `opine` instance with no breaking changes
`router.js` exports an `opine` `Router` that can be mounted onto other `opine` apps. This will help in our implementation of the SaaS app module that requires an app prefix to be added to all of the routes.
> refactor(app-opine): move routing into separate opine Router instance

- packages/core/lib/cache/store.js
- packages/core/lib/queue/queue.js
The purpose of these checks are to ensure the names are URI friendly characters.
Both of these characters are allowed in a URI, but not have a reserved purpose
according to rfc3986 section 2.3:
```
2.3.  Unreserved Characters
Characters that are allowed in a URI but do not have a reserved
purpose are called unreserved.  These include uppercase and lowercase
letters, decimal digits, hyphen, period, underscore, and tilde.
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
```
> feat(core): allow ~ and _ in queue and cache store names

- packages/core/utils/config-schema.js
`link` is meant to be optional for `plugins`. The use case is that some plugins load data, via `load`, but don't augment the adapter during `link`.
A workaround is to just implement `link` as a passthrough:
```js
{
link: () => next => next
}
```
> fix(core): link is optional for plugins

- packages/port-queue/mod.js
Looks like `index` is defined on the port and adapters, but not exposed on the adaper parser. This PR exposes it.
> fix: expose index api on adapter parser

- packages/core/lib/cache/store.js
- packages/core/lib/cache/store_test.js
- packages/core/lib/data/db.js
added map in core of data/index to convert descending flag to boolean to pass properly to adapter.
also found failing test on cache - checking for special characters on cache name.
Cache names must begin with lowercase letters
https://docs.hyper.io/create-cache-store
> add cast to descending param and fixed cache name check (#257)

- packages/port-data/mod.js
- packages/port-data/mod_test.js
In this pull request, I updated the data port schema to support `fields` for the query method, and created a union type for the `sort` prop in the query method. This will enable these features to be active for adapters.
The fields prop works like a select statement where you can specify the specific properties on the document you would like to return.
The sort allows clients to specify how they want the returning documents sorted in either ASC or DESC order by providing an array of objects: [{id: 'DESC'},{ title: 'ASC'}]
By specifying these two query props, the adapters can implement the details of the specification
> refactored spec for query documents (#304)

- packages/core/deps.js
- packages/core/lib/cache/doc_test.js
When testing the ttl feature of the cache port, and error was returned unable to use the current `ms` lib, changed to the deno version of the `ms` lib and core tests seem to work.
> fixed cache ttl and ms function (#308)

- packages/connect/nodejs/index.js
Fixed bug with hyper connect, when an error is returned, to only return the result if the result is in JSON.
> fix: if error response is json return json (#369)

- packages/test/data/list-documents.js
Changed data list tests to use bulk as it is supposed to work
> fix: leverage bulk feature for data list test

- packages/core/lib/data/db.js
- packages/core/lib/data/db_test.js
- packages/core/lib/data/doc.js
- packages/core/lib/data/doc_test.js
Recall we said `_id` only needs to come back on actual documents. So I removed `_id` from `create` `update` `bulk` and `remove` results on the `data` service, leaving only the `id` (which is set to `_id` if not defined)
Also ran `hyper-test` and realized `apricot` broke a test case for `no document`, so added in a fix for that to satisfy the test.
#407
> fix(core): don't return _id on create, update, bulk, remove data

- packages/test/data/query-documents.js
`core` is adding an extra key `id` or `_id` to each document, so we take this into account for `hyper-test` for `apricot` release
This will need to be removed as part of the `blueberry` phase
> fix(test): hyper test take into account extra _id key

- .github/workflows/test-connect.yml
- packages/connect/src/utils/hyper-request.ts
- packages/connect/tests/hyper-request.ts
When attempting to first use the connect client immediately after initialization (**with Node v14.x**), we receive the following error:
`The "key" argument must be an instance of Buffer, TypedArray, or DataView. Received type string ('...')`
Given that the most recent Node runtimes for AWS lambda is still `v14.x` and is likely to be so for a while longer (_reference needed_), it would be nice to get it to run in `v14.x`.
- Added Node v14 to the testing matrix
- Added a failing test to demonstrate issue when using newly initialized connect client under Node v14
- ~Added `crypto` to as an explicit dependency since this was imported in code~ (Thanks for the info @TillaTheHun0) 
- Converted secret into buffer before invoking `crypto.createSecretKey`. For some reason this worked with a string …
> Make hyper-connect compatible with Node 14.x

- packages/core/lib/data/db.js
- packages/core/lib/data/db_test.js
- packages/core/lib/data/doc.js
- packages/core/lib/data/doc_test.js
The port enforces `id` to come back on most apis, so mapping in core is not needed, as it's a the job of adapters to ensure id is returned in that case. Otherwise the port will produce an error.
> refactor(core): do not map to id where it is enforced by the port

- packages/test/data/bulk-documents.js
- packages/test/data/create-document.js
- packages/test/data/list-documents.js
- packages/test/data/query-documents.js
- packages/test/data/remove-document.js
- packages/test/data/retrieve-document.js
- packages/test/data/update-document.js
This PR updates `hyper-test` to create documents with `_id` and to test for the presence of `_id` on documents as opposed to `id`.
To align with the rest of the blueberry releases. I propose we also major bump `hyper-test` to `v2.0.0`
This is meant to be the gold standard for testing adapters for correctness and completion.
Closes #421
> refactor(test)!: id -> _id in data test suite #421

- packages/core/lib/data/doc.js
- packages/core/lib/data/doc_test.js
Closes #412 
Closes #413 
This PR makes it so `core` does not map `id` on the doc to `_id` and vice versa. **The outbound mapping is still kept**
BREAKING CHANGE
I propose we bump `core` to `v2.0.0` on this change.
> feat!(core): remove inbound id mapping #412

- packages/app-opine/utils.js
before, `message` was mapped to `msg` only if `status` was set. Otherwise, error was sent back, which could be anything.
This PR makes it such that every error response from `app-opine` will have `ok: false` and `msg`, and then whatever else is included on the `error` from `core`
> fix(app-opine): consistently construct error sent back to client

- packages/port-storage/dev_deps.js
- packages/port-storage/dev_deps_lock.json
- packages/port-storage/mod.js
- packages/port-storage/mod_test.js
- packages/port-storage/scripts/test.sh
This PR makes it such that `putObject` supports both of the following function schemas:
```ts
type PutObjectUploadSchema = ({ bucket: string, object: string, stream: Buffer, doReturnUrl?: false }) => Promise<{ ok: boolean }>
type PutObjectSignedUrlSchema = ({ bucket: string, object: string, doReturnUrl: true }) => Promise<{ ok: boolean, url: UrlString }>
```
If `stream` is provided, `doReturnUrl` must be `falsey`, and `putObject` will need to do a file upload and not return a signed url. If `doReturnUrl` is true, `stream` must not be provided, and a signed url must be returned.
We can make `doReturnUrl` be anything, I just picked a name to work with. We can change if we have a better name for it. Maybe `doReturnSignedUrl`?
Also fixed a little bug on `listBuckets` that I discovered when …
> feat(port-storage): overload putObject to support file upload and signed url flow #444

- packages/port-cache/deps.js
- packages/port-cache/mod.js
- packages/port-crawler/deps.js
- packages/port-crawler/mod.js
- packages/port-data/deps.js
- packages/port-data/mod.js
- packages/port-hooks/deps.js
- packages/port-queue/deps.js
- packages/port-queue/mod.js
- packages/port-search/deps.js
- packages/port-search/mod.js
- packages/port-storage/deps.js
- packages/port-storage/mod.js
- packages/port-storage/mod_test.js
TL;DR: there shouldn't be any breaking changes in this PR, besides removing the unused `error` fields on some Cache port methods. Everything else should be backwards compatible. Not a lot of code changes (most of the diff is the duplicated utility), but need to explain my reasoning.
---
Previously, adapters would send back resolved promises for successful responses and rejected promises for error responses. With #468, that paradigm has shifted, such that an _unhandled_ exceptions returns as a rejected promise and a _handled_ exception should returned as a resolved promise.
Zod schemas wrap each adapter method, that validate the return type of _resolved_ responses. Since errors were previously not resolved responses, these were not validated. Now they run through the zod schema validation …
> fix: update all ports to support success + error union response #468

- packages/app-opine/deps.js
- packages/app-opine/dev_deps.js
- packages/app-opine/utils.js
Closes #482 
Also pulled in `isHyperErr` from `hyper-utils`
> fix(app-opine): sanitize resolved and rejected errors from core #482

- packages/core/lib/utils/mod.js
Something I noticed when wiring everything up into hyper cloud. Now that events are being triggered (and logged) for all _handled_ responses from adapters, which includes handled hyper errors, it would be nice to see what events correspond to errors.
Right now, this would branch would run for both handled errors and fuzzy-mapped errors from core. I could the case for only triggering for fuzzy mapped errors ie `data.originalErr is not nil`.
> feat(core): indicate error in event payload from core #468

- packages/connect/deno/mod.ts
- packages/connect/deno/types.ts
- packages/connect/src/types.ts
Cleanup types based on what i've seen using it in the remix stack, and so Deno typechecking doesn't throw.
> fix(connect): cleanup types and make more accurate

- packages/core/lib/data/db.js
- packages/core/lib/data/db_test.js
- packages/core/lib/data/doc.js
- packages/core/lib/data/doc_test.js
- packages/core/lib/utils/err.js
- packages/core/lib/utils/mod.js
- packages/test/data/query-documents.js
Just removing code that mapped _id -> id on outbound requests
Closes #420
> chore(core): remove id monitoring and mapping _id -> id on outbound

- packages/connect/deno/mod.ts
- packages/connect/deno/shim.node.ts
- packages/connect/deno/types.storage.deno.ts
- packages/connect/deno/types.storage.node.ts
- packages/connect/deno/types.ts
- packages/connect/node/harness/cjs/index.js
- packages/connect/node/harness/cjs/package.json
- packages/connect/node/harness/esm/index.js
- packages/connect/node/harness/esm/package.json
- packages/connect/node/package.json
- packages/connect/package.json
- packages/connect/yarn.lock
`undici` doesn't export certain modules for Node versions <16
See this issue https://github.com/nodejs/undici/issues/1416#issuecomment-1119548066
Subseqeuntly this broke Node 14, which is needed to be supported right now
So we had to swap to dependencies that supported Node 14, Le Sigh
This led to cascading changes, including the type returned by `hyper.storage.download` diverging between Deno and Node, which is why there are separate types files for each.
> fix(connect): fix node integration as indicated broken by CI #509

- packages/app-opine/api/storage.js
- packages/app-opine/dev_deps.js
- packages/app-opine/test/utils_test.js
- packages/app-opine/utils.js
- packages/port-storage/dev_deps.js
- packages/port-storage/mod.js
- packages/port-storage/mod_test.js
This PR implements support for the presigned url flow as described in #519 
`port-storage` now accepts a `useSignedUrl` option, as a boolean.
`app-opine` route for `GET /storage/:name/*` now accepts a `useSignedUrl` query parameter, parses it to a boolean, and then will pass it to core.
So to get a presigned GET url from hyper storage, you would have a URL like:
`http://localhost:6363/storage/foo/bar.png?useSignedUrl=true`
I also updated some dev dependencies and cleaned up the test and added coverage to each. `deno fmt` also made a bunch of formatting changes.
once these are release, I can bump core and subsequently support this in core.
> feat: add support for useSignedUrl for getObject #519

- packages/connect/deno/services/cache.ts
- packages/connect/deno/services/data.ts
- packages/connect/deno/services/info.ts
- packages/connect/deno/services/queue.ts
- packages/connect/deno/services/search.ts
- packages/connect/deno/services/storage.ts
- packages/connect/deno/tests/storage.ts
- packages/connect/deno/types.storage.deno.ts
- packages/connect/deno/types.storage.node.ts
- packages/connect/deno/types.ts
- packages/connect/deno/utils/hyper-request.ts
This PR adds the ability to pass an `StorageDownloadOptions` object to `storage.download`. Right now the only option is `useSignedUrl`, which is then passed directly to `hyper-request` and added as query parameters on the request.
Closes #522
Also `deno fmt` formatted lots of things.
> feat(connect): support useSignedUrl for storage.download #522

- packages/connect/deno/mod.ts
- packages/connect/deno/services/storage.ts
- packages/connect/deno/tests/storage.ts
- packages/connect/deno/types.storage.deno.ts
- packages/connect/deno/types.storage.node.ts
- packages/connect/deno/types.ts
BREAKING CHANGE: removed `StorageDownloadOptions` from `storage.download`.
Consumers should instead use `storage.signedUrl(name, { type: 'download' })
> feat(connect): add signedUrl api on storage service #524

- .github/workflows/publish-image-nano.yml
- images/nano/.gitignore
- images/nano/bin/index.js
- images/nano/package-lock.json
- images/nano/package.json
With this PR, node developers will be able to use `hyper-nano` using `npx`:
```
npx hyper-nano --experimental --data --cache --domain=foo ...
```
Closes #530
>  feat(nano): add npx capability #530 

- packages/connect/deno/dev_deps.ts
- packages/connect/package.json
- packages/connect/yarn.lock
Closes #548 
Simply bump deps, in particular `undici` to the version that supports Node 18
> chore(connect): bump deps #548

- packages/app-express/api/mod.ts
- packages/app-express/api/search.test.ts
- packages/app-express/api/search.ts
- packages/app-express/middleware/json.test.ts
- packages/app-express/middleware/json.ts
- packages/app-express/middleware/legacyGet.test.ts
- packages/app-express/test-utils.ts
Closes #562 
Also made the `json` middleware more flexible, by it defaulting to parsing the request body as JSON, even if `content-type` is not provided on the request.
> feat(app-express): add search routes and start of test #562

- packages/app-express/api/storage.ts
- packages/app-express/deno.lock
- packages/app-express/deps.ts
- packages/app-express/dev_deps.ts
- packages/app-express/middleware/legacyGet.ts
- packages/app-express/middleware/object.ts
- packages/app-express/test-utils.ts
- packages/app-express/types.ts
This PR implements the `putObject` api on the `app-express` hyper storage api. I used `multer` to handle `multipart/form-data` uploads.
It also implements the ability to accept binary data in the body, using the url path as the object name to pass to core, as described in #571.
Closes #571
I still need to write the unit tests for the middlewares and routes, but wanted to get this PR up before it got too big.
Something that was particularly cool about this implementation:
The app must provide a `Deno.Reader` to hyper core, and since this app is built using `Express` I had to think of a way to convert an Express Request body into a `Deno.Reader` while not losing performance benefits ie. by buffering the body into memory first or something like that. This turned out to be fairly …
> feat(app-express): implement putObject endpoints and support streaming body #569 #556 #571

- packages/app-express/api/storage.test.ts
- packages/app-express/api/storage.ts
- packages/app-express/deno.jsonc
- packages/app-express/deno.lock
- packages/app-express/deps.ts
- packages/app-express/dev_deps.ts
- packages/app-express/harness.ts
- packages/app-express/utils.ts
Closes #554
Also made it such that `putObject` expects to pass a `ReadableStream` to `core`. Which makes streaming requests into core much simpler and performant.
What's left is to beef up tests on the driving app-express adapter and it is done 🎊
> App Express: getObject and associated tests. `Deno.Reader` -> `ReadableStream`

- .github/workflows/image-nano.yml
- images/nano/Makefile
- images/nano/bin/index.js
- images/nano/deno.lock
BREAKING CHANGE
closes #537 
This PR changes `hyper-nano` on Node to download the hyper-binary into the current working directory, which is to say wherever `npx` is ran from, typically the project directory. This is similar behavior to tools like the NextJS CLI when running `next build`.
With this, installing dependencies with `yarn` will not blow away the binary and any persisted data in the `__hyper__` directory, as described in #537 
This is breaking change, since users will need to add the `hyper-nano` binary and the `__hyper__` directory to their `.gitignore`.
---
This PR also makes new versions of `hyper-nano` be published to our S3 bucket with a version suffix. This way, each `hyper-nano` version has a corresponding binary version to be downloaded from S3.
> Version hyper-nano binaries and place artifacts in the current working directory

- packages/port-data/mod.test.ts
- packages/port-data/port.ts
Adds the ability to pass a filter, when creating an index on documents in a hyper data service. Documents are only included in the index, if they match the filter associated with the index.
This is common feature across document databases that reduces index storage usage and index performance ie. [Couch](https://docs.couchdb.org/en/stable/api/database/find.html#partial-indexes), and [Mongo](https://www.mongodb.com/docs/manual/core/index-partial/#partial-indexes)
> feat(port-data): add partialFilter option to indexDocuments

- packages/connect/deno/mod.ts
- packages/connect/deno/services/cache.ts
- packages/connect/deno/services/data.ts
- packages/connect/deno/services/search.ts
- packages/connect/deno/services/storage.ts
- packages/connect/deno/tests/cache.test.ts
- packages/connect/deno/tests/data.test.ts
- packages/connect/deno/tests/search.test.ts
- packages/connect/deno/tests/storage.test.ts
- packages/connect/deno/types.ts
Also exposed `create` and `destroy` on `storage`
> Require confirmation on hyper.*.destroy on `hyper-connect`

- .gitpod.Dockerfile
- packages/connect/deno.json
- packages/connect/deno/mod.ts
- packages/connect/deno/services/queue.ts
- packages/connect/deno/tests/cache.test.ts
- packages/connect/deno/tests/data.test.ts
- packages/connect/deno/tests/hyper-verify.test.ts
- packages/connect/deno/tests/queue.test.ts
- packages/connect/deno/tests/search.test.ts
- packages/connect/deno/tests/storage.test.ts
- packages/connect/deno/types.ts
- packages/connect/node/tests/hyper-verify.js
> connect: Add `queue.create` and `queue.destroy`

- packages/app-express/api/cache.test.ts
- packages/app-express/api/crawler.test.ts
- packages/app-express/api/data.test.ts
- packages/app-express/api/queue.test.ts
- packages/app-express/api/search.test.ts
- packages/app-express/api/storage.test.ts
- packages/app-express/middleware/json.test.ts
- packages/app-express/middleware/legacyGet.test.ts
- packages/app-express/types.ts
- packages/core/deno.lock
- packages/core/lib/cache/doc.ts
- packages/core/lib/cache/mod.test.ts
- packages/core/lib/cache/store.ts
- packages/core/lib/data/db.ts
- packages/core/lib/queue/mod.test.ts
- packages/core/lib/queue/queue.ts
- packages/core/lib/utils/err.test.js
- packages/core/lib/utils/mod.ts
- packages/core/mod.test.ts
Closes #621
Also fixes an issue with test harness not closing after each test in the `app-express` App adapter.
> fix(core): pass specific status to HyperErr on known errors and bubble as non fatal #621
