hyper63/hyper

- README.md
- packages/core/lib/cache/store.js
- packages/core/lib/cache/store_test.js
- packages/core/package.json
added validation rules to core for `cache` name
> #6 cache store name validation

- packages/adapter-elasticsearch/adapter.js
- packages/adapter-elasticsearch/adapter_test.js
closes #135 #162
I believe this implements the spec. Please let me know what changes are needed
> fix(adapter-elasticsearch): query implement key/value filter api

- packages/app-opine/api/crawler.js
- packages/app-opine/deps.js
- packages/app-opine/lib/upload.js
- packages/app-opine/router.js
- packages/app-opine/test/crawler-delete_test.js
- packages/app-opine/test/crawler-get_test.js
- packages/app-opine/test/crawler-start_test.js
- packages/app-opine/test/crawler-upsert_test.js
Added endpoints for crawler port
> feat (app-opine): add crawler endpoints (#270)

- packages/app-graphql/README.md
- packages/app-graphql/lib/graphql/Crawler/crawler.schema.js
- packages/app-graphql/lib/graphql/CrawlerResult/crawler-result.schema.js
- packages/app-graphql/lib/graphql/Query/query.schema.js
- packages/app-graphql/lib/graphql/schema.js
- packages/app-graphql/schema.graphql
I know there will be issues with this one, but I wanted to take a stab at it, so I added crawler to app-graphql, I hope I got some of it right! :)
> feat (app-graphql): added crawler schema to graphql #(272)

- README.md
- images/nano/deps.js
- package.json
- packages/app-opine/router.js
- packages/app-opine/test/mod_test.js
> chore update nano with latest app-opine package and changed hyper #329

- packages/test/data/list-documents.js
- packages/test/data/query-documents.js
- packages/test/import_map.json
- packages/test/mod.js
fixed sorting with couchdb, you need an index!
> fixed sort test (#333) - #337

- packages/connect/README.md
- packages/connect/nodejs/data.js
Added the `index` function with `hyper.data` module
> added index method to hyper connect nodejs #362

- packages/connect/egg.json
This pull request is just to change the egg json to include all source files
> fix: updated egg json to include all deno src files #381

- packages/test/mod.js
Issue https://github.com/hyper63/hyper/issues/400
> list-documents tests run last because they rely on prior functions

- packages/core/lib/data/doc.js
- packages/core/lib/data/doc_test.js
> feat(core): set ids on doc passed to adapter #414

- .github/workflows/test-app-opine.yml
- .github/workflows/test-connect.yml
- .github/workflows/test-image-nano.yml
- .github/workflows/test-port-cache.yml
- .github/workflows/test-port-crawler.yml
- .github/workflows/test-port-data.yml
- .github/workflows/test-port-queue.yml
- .github/workflows/test-port-search.yml
- .github/workflows/test-port-storage.yml
- .github/workflows/test-test.yml
- .github/workflows/test-utils.yml
- .github/workflows/tests-client-nodejs.yml
- .github/workflows/tests-core.yml
Should fix the issue we ran into on #417 with the checks not running on this repo from a PR from a fork.
> ci: run test workflows on prs

- packages/connect/deno/deps.ts
- packages/connect/deno/mod.ts
set version of ramda to 0.27.1 for deno connect.
> fix(connect): set ramda version to 0.27.1 #426

- packages/app-opine/deps.js
- packages/app-opine/dev_deps.js
- packages/app-opine/router.js
> chore(app-opine): send back beta on root route #489

- packages/port-data/dev_deps.js
- packages/port-data/mod.js
- packages/port-data/mod_test.js
> fix(port-data): make sort schema for queryDocuments more strict #484

- packages/core/lib/storage/buckets.js
> fix(core): fix typo in storage event #503

- packages/connect/deno/mod.ts
- packages/connect/deno/tests/hyper-verify.ts
- packages/connect/deno/utils/hyper-verify.ts
- packages/connect/package.json
- packages/connect/src/index.ts
- packages/connect/src/lib.d.ts
- packages/connect/src/utils/hyper-verify.ts
- packages/connect/tests/hyper-verify.ts
- packages/connect/tsconfig.json
- packages/connect/yarn.lock
Sometimes, TS in Node can be a real drag
> fix(connect): export createHyperVerify on node and improve jsdoc

- packages/connect/deno/types.ts
> fix(connect): make search.query options optional #535

- packages/core/lib/cache/doc_test.js
- packages/core/lib/data/doc_test.js
- packages/core/lib/utils/mod.js
> fix(core): remove backwards compatibility and passthrough for new get shape #546

- packages/app-express/api/mod.ts
- packages/app-express/api/queue.test.ts
- packages/app-express/api/queue.ts
> feat(app-express): add queue routes and start of tests #564

- packages/connect/deno.json
- packages/connect/deno/dev_deps.ts
- packages/connect/deno/mod.ts
- packages/connect/deno/tests/hyper-request.ts
- packages/connect/deno/utils/hyper-request.ts
> refactor(connect): use fetch shim so as to not pass a Request object to fetch #566

- packages/app-express/api/storage.test.ts
- packages/app-express/api/storage.ts
- packages/app-express/deps.ts
> test(app-express): start ptObject tests #556 #569

- contributing.md
adds oss to the contributing.md link
> adds oss to contributing.md link
